project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - CA.qmd
    - CCA.qmd
    - dcCA.qmd
    - recscal.qmd
    - recscal_cca.qmd
    - recscal_dcca.qmd

website:
  title: "The theory of multivariate analyses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CA.qmd
        text: Correspondence analysis (CA)
      - href: CCA.qmd
        text: Canonical CA (CCA)
      - href: dcCA.qmd
        text: Double constrained CA (dc-CA)
      - href: recscal.qmd
        text: Reciprocal scaling (CA)
      - href: recscal_cca.qmd
        text: Reciprocal scaling (CCA)
      - href: recscal_dcca.qmd
        text: Reciprocal scaling (dc-CA)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5

bibliography: references.bib